# Configuration file for StatsPE

# Enabled Stats:
JoinCount: true
KillCount: true
DeathCount: true
KickCount: true
# OnlineTime won't be finish for a long time.
OnlineTime: false
BlockBreakCount: true
BlockPlaceCount: true
ChatCount: true
FishCount: true
BedEnterCount: true
EatCount: true
CraftCount: true

# Set default data provider for StatsPE
# Available Providers: MySQL, JSON (Use this if you want YAML)
Provider: JSON

# MySQL Settings (Only configure this if you are going to use MySQL data provider)
  address: "MySQL.example.net"
  port: "3306"
  user: "YourUsernameGoesHere"
  password: "YourPasswordGoesHere"
  database: "YourDBNameGoesHere"
