# Configuration file for StatsPE

# Enabled Stats: true/false
JoinCount: true
KillCount: true
KD: true
DeathCount: true
KickCount: true
# OnlineTime has not been implemented
OnlineTime: false
BlockBreakCount: true
BlockPlaceCount: true
ChatCount: true
FishCount: true
BedEnterCount: true
EatCount: true
CraftCount: true

# Enable/Disable the Auto-Updater Feature.
Auto-Update: true
Shutdown-Message: "Restarting Server due to a software update!"
# Time Format used for Stats like last and first Join
# Further information about this on this page:
# http://php.net/manual/de/function.date.php
# Default: "H:i:s d.m.Y" = Hour:Minute:Seconds Day.Month.Year
# Example: 12:00:63 22.07.2016
TimeFormat: "H:i:s d.m.Y"

# Set data provider for StatsPE
# Available Providers: MySQL, JSON
Provider: JSON

# MySQL Settings (Only configure this if you are going to use MySQL data provider)
MySQL:
  address: "MySQL.example.net"
  port: 3306
  user: "ExampleUser"
  password: "12345678"
  database: "StatsPE"
